### ISSUE TITLE
nixcon 2024 png logo is not the correct one

### ISSUE THREAD

**Issue by zmberber** [nixcon/2024.nixcon.org#10]
if you compare the png of the nixcon 2024 logo to [the nixcon 2024 logo on the official website](https://2024.nixcon.org/), it is not the same one!  it seems more like a prototype.

maybe let @pinpox upload the svg here and we can do a png from that.

**Comment by zmberber** [comment]
ah wait, the svg is already there, and it is the correct one.  so i am only talking about the png

**Comment by picnoir** [comment]
I'm confused. Where do you see this faulty PNG?

Are you talking about the unused one in this repo? If so, you shouldn't see it on the website. Feel free to remove it.

**Comment by zmberber** [comment]
https://github.com/nixcon/2024.nixcon.org/blob/main/themes/nixcon-2024/static/logo.png

**Comment by zmberber** [comment]
it is not used on the website, but other communities have taken the logo from here.  i would remove it in a PR, or change it to a proper one in a PR
